version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
